@startuml CodeUnits-Overview
title CodeUnits of SCBuilder

[SCBuilder]
note as SCBuilderNote
  SCBuilder is the builder image to get used with the ScriptCollection.
end note
SCBuilder .. SCBuilderNote


@enduml