#!/bin/bash
set -e

# Entrypoint for the SCTaskRunnerAndroid image: runs the SCTaskRunnerServer (see SCTaskRunnerAndroidCore.py), which
# listens permanently for remote-build-jobs sent by ScriptCollection's TFCPS_RemoteBuild (see the remote-build-article
# in ScriptCollection's reference). Configuration is read from environment-variables by SCTaskRunnerAndroidCore.py
# itself (SCTaskRunner_Username/_Password/_Port/_CertificateFile/_CertificateKeyFile, see the ReadMe).

# Memory-budget of a gradle-build.
# Why this is done by the runner and not by the built repository: the amount of memory a build may use is a property of
# this container (its memory-limit), not of the app which is built - a repository can not know on which runner it will be
# built. On top of that, a flutter-project brings an android/gradle.properties generated from flutter's template which
# requests 8 GiB of heap plus 4 GiB of metaspace. That exceeds the limit of a typical runner-container, so the kernel
# kills the gradle-daemon while it is building and gradle reports the (very unspecific) error
# "Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)".
# Why it is written into $GRADLE_USER_HOME: of the gradle.properties-files gradle reads, the one in $GRADLE_USER_HOME has
# precedence over the one of the project, so this is the only place from which the values of flutter's template can be
# overruled without modifying the repository which is built.
# Why it is written on every start instead of being baked into the image: $GRADLE_USER_HOME is a mounted volume in the
# recommended deployment (it is the gradle-download-cache), and a mount hides whatever the image put there.
# The values are environment-variables so that a runner with a different memory-limit can be configured without a
# rebuild; the defaults are chosen so that a build fits into a container with 6 GiB.
gradle_max_heap="${SCTaskRunner_GradleMaxHeap:-2g}"
gradle_max_metaspace="${SCTaskRunner_GradleMaxMetaspace:-768m}"
gradle_max_workers="${SCTaskRunner_GradleMaxWorkers:-2}"
mkdir -p "${GRADLE_USER_HOME}"
cat > "${GRADLE_USER_HOME}/gradle.properties" <<EOF
# Generated by EntryPoint.sh of SCTaskRunnerAndroid on every container-start. Do not edit: the file is overwritten.
# See the comment in EntryPoint.sh for why these values are set here instead of in the repository which is built.
org.gradle.jvmargs=-Xmx${gradle_max_heap} -XX:MaxMetaspaceSize=${gradle_max_metaspace} -XX:+HeapDumpOnOutOfMemoryError
# No reusable daemon: every job gets a fresh workspace which is deleted again as soon as the job is deleted, so a daemon
# which outlives a job has its working-directory removed underneath it. Keeping one alive would also occupy its whole
# heap while the runner packs the (potentially multi-gigabyte) result-archive of the finished job.
org.gradle.daemon=false
# Parallel project-execution and a large worker-pool multiply the amount of processes which hold memory at the same time.
# An android-app-build of a flutter-project is a single module, so parallelism buys close to nothing here anyway.
org.gradle.parallel=false
org.gradle.workers.max=${gradle_max_workers}
# File-system-watching keeps state about a workspace which is deleted after the job, so it can never be reused - it only
# costs memory and inotify-watches here.
org.gradle.vfs.watch=false
# Compile kotlin inside the gradle-process instead of forking a separate kotlin-daemon-JVM. A flutter-app contains very
# little kotlin (usually just the activity), so it fits easily, and it avoids a second JVM with its own heap.
kotlin.compiler.execution.strategy=in-process
EOF

exec python3 /usr/local/bin/SCTaskRunnerAndroidCore.py
